### ISSUE TITLE
Prune out any deprecated stuff

### ISSUE THREAD

**Issue by cppchriscpp** [cppchriscpp/TravelPortals#11]
Just need to take a pass through the plugin and remove deprecated methods, etc. I see a lot of .getTypeId && setTypeId. May need to change configs, too. What is the plan for this deprecation?

**Comment by Phoenix616** [comment]
This should be implemented with ce7f588c now. Old numeric ids will still work as long as Bukkit does not remove the deprecated methods but you can use the enum names directly now and they are used as the default setting.
