### ISSUE TITLE
Door bug

### ISSUE THREAD

**Issue by 5WAP** [cppchriscpp/TravelPortals#14]
If you make a Portal and close the door. Players can bug through the door so that the portal works teleports them. If a player do this and is teleportet to another portal with a closed door, they die.

That happens if you only want to go near the portal, you do not have to force anything to get bugged.

**Comment by cppchriscpp** [comment]
This sounds a bit like a Craftbukkit/spigot bug... not sure that I'm going to be able to do anything about this one. In addition, any situation like that I've ever seen, you've been able to open the door and get out. (Though if the hosting server is lagging, and it takes 5-10 seconds to get the world load, that could make things much worse. There's nothing I can really do with the plugin to fix that.) 

To keep digging into this, I could use a bit more information. Could you share what server software you are running this against, and if possible a list of plugins? (In case there is some sort of conflict)

**Comment by 5WAP** [comment]
Yeah we are using spigot with standart Plugins, like WorldGuard, WorldEdit, ChestShop, Essentials.
The Server does not lag that is certain.

You will be Teleportet if you stay to near to the door of the Portal. You do not have to touch the "water".

**Comment by cppchriscpp** [comment]
Ugh, I didn't really give as much detail as I should have. If possible, could you share what version of spigot you use? I believe you can use the /version command to get it in-game.

That's not a bad list of plugins, and I don't think I really need more, but if you get the chance could you share the output of the "plugins" command on the server? (/plugins client side, but then you can't copy/paste as easily) It's a bit more cohesive than a list from memory... again if this one's too much trouble, don't bother.

I'll be honest, life has me pretty busy right now. I don't think I'll get the chance to experiment with this until at least Thursday, but I won't forget about it. (And it's fine to keep pinging if you haven't heard anything in a few days)

**Comment by 5WAP** [comment]
The problem could be fromt he Plugin LWC: https://github.com/Hidendra/LWC/issues/908

Some other Servers report this issue as well. But i appreciate your support for the Problem. I guess it will be fixed if LWC is fixed.

**Comment by cppchriscpp** [comment]
Just wanted to say thanks for following up! That will likely help others with similar problems, and gives me a hint as to what to suggest.
