### ISSUE TITLE
TravelPortals: Can't name portal

### ISSUE THREAD

**Issue by KrystalKane** [cppchriscpp/TravelPortals#22]
I have my own Minecraft server running version 1.14.4. I downloaded your plugin Travel Portals plugin. The issue I have is that I get the portal to work in terms of building the structure and having the water appear. 

However, when I am in the water to name the portal it comes up with "No Portal Found" Could I have done something wrong? 

Any help would be appreciated.

Looking forward to hearing from you and I wish you all the best :)

**Comment by cppchriscpp** [comment]
Hello!

I am hoping for a little more information on the server and plugin versions you are using. Could you please reply here with that information?

One way to find them is by looking at the server log. You should see two lines like these: 

```
[10:53:05] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-e5e8eec (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

and, further down

```
[10:53:13] [Server thread/INFO]: [TravelPortals] Loading TravelPortals v2.4-SNAPSHOT (build 11)
```

That might help us narrow in on the issue. To note, if you're running TravelPortals v2.3, please try upgrading. Minecraft made some major changes around that time, and the plugin had to be upgraded to match.

To note for myself and Phoenix616: I did quickly try running the latest TravelPortals on dev.bukkit (https://dev.bukkit.org/projects/travelportals/files/2625299) against the latest craftbukkit server (1.14.4-R0.1-SNAPSHOT - https://getbukkit.org/download/craftbukkit) and was able to create and use portals successfully. I didn't try snapshot versions from jenkins.

**Comment by KrystalKane** [comment]
here is what I have found in the logs 

[19:24:48] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-e5e8eec (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

[19:25:01] [Server thread/WARN]: Plugin TravelPortals v2.3 (build 8) does not specify an api-version.

I thought on Bukkit I downloaded the latest version of TravelPortals?

Thank you so much btw for helping me get this to work! 

Kindest regards,

Kris

**Comment by cppchriscpp** [comment]
So, it looks like you have an outdated version of TravelPortals, so that's likely the source of the problem. You want 2.4: https://dev.bukkit.org/projects/travelportals/files/2625299

The bukkit site lists them in a strange order, likely because this build was marked as an alpha build rather than release. I'm going to change that now so it hopefully doesn't confuse others. 

Let me know if that takes care of it for you!

**Comment by KrystalKane** [comment]
That has sorted the issue!

Thank you so much for helping me out on this now me and my 20+ year old friends are loving the plugin! This plugin is perfect for making my portal room! If you fancy you are more than welcome to join my server! :) you are more than welcome.

Also if you need any help with graphic design or anything let me know as that is what I do :)

Thanks again and have a nice day!

**Comment by cppchriscpp** [comment]
Glad to help!
