### ISSUE TITLE
Teleport players when entering portal

### ISSUE THREAD

**Issue by Flying--Dutchman** [cppchriscpp/TravelPortals#33]
Should we teleport the player upon entering the portal instead when the player tries to leave it?

Would give a more "portal" like feeling.

Maybe also usefull for #32

**Comment by Phoenix616** [comment]
Pretty sure its already made to work like that, at least when the move event listener mode is used.  (When the polling is used it just depends on the player position and whether or not they are in the portal at the poll time)

**Comment by Flying--Dutchman** [comment]
Yep, seems so.
