### ISSUE TITLE
Only use on specific worlds

### ISSUE THREAD

**Issue by Flying--Dutchman** [cppchriscpp/TravelPortals#35]
I'm altering the code so that portals can only be build and used in specific worlds.
Should the config option be `active-worlds` or the negated form `disabled-wolds`?

Personly I would prefer `active-worlds`, but then ofcourse it would break existing setups.

So 2 options:
1. Use `disabled-worlds`
2. If no worlds are set with `active-worlds`, every world is allowed

**Comment by Phoenix616** [comment]
Why not just not give the create/use permissions in those worlds?

**Comment by Flying--Dutchman** [comment]
Indeed, thats an option with plugins like LuckPerms 👍
